### PR TITLE
Arima enzymes for Hi-C

### PR DESCRIPTION
**Pull request by gtrichard**
Hello :)

Just a small merge request to add Arima Genomics double enzymes cut sites to the pipeline.

Building of matrices with fixed binsize is working. I need to test yet if restriction enzyme resolution matrices are building correctly and if fixed bin size QCs are allright.

@LeilyR  would you be able to tell me if it's the correct way to use multiple enzymes in HiCExplorer? First time I'm trying it.

### CODE REVIEW

**Comment by gtrichard** [comment]
From the first checks, the QCs aren't precise with this patch. I'm testing if it's similar with restriction enzyme resolution matrices. The file below contains the QCs for a sample with fixed binsize.

[GLLR11_QC.zip](https://github.com/maxplanck-ie/snakepipes/files/5787082/GLLR11_QC.zip)

**Comment by LeilyR** [comment]
Thanks @gtrichard , it is definitely an improvement to our pipeline. Although I will consider making this more general in the future.  I put it in my todo list.

**Comment by gtrichard** [comment]
Bad news, it works fine in fixed binsize mode (because hicFindRestSite is skipped). 

In RF resolution mode (which gives nice QCs compared to fixed binsize mode), the pipeline crashes. This is because hicFindRestSite cannot take multiple enzymes at once as input. So one needs to perform hicFindRestSites for each enzyme sequence (when more than one is provided) and then cat the two beds.

Perhaps it would be a better way to be able to give more than one enzyme sequence to HiC SnakePipes and that the findRestSite rule scales automatically depending on the number of given enzymes. So there would not be a single "Arima" option. We would need to add HinfI and run the SnakePipes with `DpnII HinfI` as the enzyme parameter.

**Comment by katsikora** [comment]
Hi guys,

is this PR still pending, or would you like to close it?
Best,
Katarzyna

**Pull request closed without merging**
