### PR TITLE
Rewrite GTF filtering

### PR DESCRIPTION
**Pull request by dpryan79**
This completely rewrites how GTF filtering is done. It's still done with grep, since that's rather convenient, but it's now done directly on the GTF file. Some of the intermediate files are no longer made, since they're not needed. The GTF is now just symlinked through if no filtering is to take place.

This needs to be tested with the RNA-seq and scRNA-seq workflows.

### CODE REVIEW

**Comment by dpryan79** [comment]
Unrelated to this PR, but discovered during testing it, there's something wrong with DESeq2 in `develop` such that it's messing up variance estimates.

**Comment by dpryan79** [comment]
We can't specify r-base build versions, since the strings differ between platforms.

**Comment by dpryan79** [comment]
I'm testing OSX environment creation locally, since the azure builds seem to just freeze for some reason.

**Comment by dpryan79** [comment]
The scrna-seq env is causing issues on OSX, where the solving step just hangs.

**Comment by katsikora** [comment]
Really? But my PR passed all the tests at the time.

**Comment by dpryan79** [comment]
I know, for whatever reason adding `readline = 7.0` to fix the skylake CPU issue in that environment is causing the OSX solver to break. The odd thing is that not adding it still installs readline 7.0 on OSX (but not linux).

**Comment by dpryan79** [comment]
The only thing remaining is to test the scRNA-seq pipeline to ensure it's not messed up by my changes.

**Comment by dpryan79** [comment]
I just spent a day trying to figure out why I was getting different results on in the scRNAseq pipeline only to realize that I wasn't, it's just that the R script that write the corrected counts was doing a bit more rounding before :P

**Comment by dpryan79** [comment]
At some point someone should probably rewrite all of the awk stuff that's used in the scRNA-seq pipeline to just a simple integrated python script, but I guess that's not a pressing need.

**Pull request merged**
