### PR TITLE
fixes #871

### LINKED ISSUE #871: filter bam rule in umi_tools.snakefile doesn't include bwa
bwa aligned bams aren't properly filtered because of this and just sym-linked

### PR DESCRIPTION
**Pull request by jeffhsu3**

### CODE REVIEW

**Comment by LeilyR** [comment]
isn't your request being taken care of in line 95? I dont see why you need to add it there.

**Comment by jeffhsu3** [comment]
I don't think the default behavior should be to symlink the unfiltered bwa aligned reads in contrast to the bowtie alignment.

**Comment by katsikora** [comment]
Thanks for pointing this one out, Jeffhsu3.

@LeilyR Jeff is right that the umi deduplication is run on samtools-filtered bam for bowtie2, while it is run on unfiltered bam for any other aligner. This is in line 64.
From line 84 onwards, umi deduplication is skipped and instead the bam files are symlinked. Again: the samtools-filtered bam file is symlinked for bowtie2, and unfiltered bam is symlinked for the other aligners. The WGBS aligners are skipped, but that's expected as I understand umi deduplication is not really implemented for this workflow. In that sense line 95 doesn't address the issue.

Do you remember if there was an original reason to use samtools-filtered bam for bowtie2, and unfiltered bam for the other aligners as input to umi deduplication? Otherwise I'd like to implement the fix.

Best,
Katarzyna

**Comment by katsikora** [comment]
@jeffhsu3 Thanks for submitting a proposal to fix the issue. After reviewing your code, I noticed it wouldn't fully address the issue for all cases. There are two cases that need fixing: 1) when umi deduplication is performed and 2) when umi deduplication is skipped and the bam file is symlinked. It's probably going to be faster to fix and test this here in house.

**Comment by katsikora** [comment]
I'm closing this PR as fixing issue #871 will require other extensive changes in the code and extensive testing. I will deal with this in a separate PR.

**Pull request closed without merging**
