### PR TITLE
Warn on invalid sample names in some workflows. Update tools in all workflows

### PR DESCRIPTION
**Pull request by dpryan79**
This needs to be tested. In particular, the various workflows need to be tested to ensure that version bumps still run. The mapping mRNA-seq workflow should do gene-level quantitation in R with tximport rather than by specifying a GTF file. This can also use selective alignment.

Tested the following:

 - [x] ATAC-seq
 - [x] ChIP-seq
 - [x] createIndices
 - [x] DNA-mapping
 - [x] HiC
 - [x] mRNA-seq
    - [x] STAR
    - [x] salmon
 - [x] noncoding-RNA-seq
 - [x] preprocessing
 - [x] scRNAseq
   - [x] Gruen
   - [x] STARsolo
 - [x] WGBS
   - [x] DSS
   - [x] metilene
   - [x] dmrseq
 - [x] Ensure a warning is displayed on names with - or starting with numbers.

Also:

 - [x] Check salmon command since tximport should be doing the gene-level aggregation.
 - [x] Selective alignment with salmon?

### CODE REVIEW

**Comment by dpryan79** [comment]
Needs a rebuild of r-raceid, for which I'm just going to try and migrate the package to conda-forge.

**Comment by katsikora** [comment]
hi Devon, if you bump raceid/seurat/monocle etc version, check that the R code is still running. Often there are changes in how the functions work etc., so the old code my break.

**Comment by dpryan79** [comment]
Certainly, I had planned to check each workflow

**Comment by katsikora** [comment]
Also, I was thinking of totally dumping that Monocle/Seurat combo in the "Gruen" mode, and keeping only RaceID. Then, adding a Seurat(3) extention to the "STARsolo" mode. This is somewhere further down on my to-do list currently, but if you want to have a look at it yourself, go ahead.

**Comment by dpryan79** [comment]
Since we can use decoys in the newer salmon versions it'd be good to allow pregenerating an index. That's quick if you don't make decoys, but slow if you do, so you probably want to avoid heavily filtering and then mapping again and again.

**Comment by dpryan79** [comment]
STARsolo is segfaulting for some reason at the moment, I'm trying to track down why.

**Pull request merged**
