### PR TITLE
Update star index path

### PR DESCRIPTION
**Pull request by dpryan79**

### CODE REVIEW

**Comment by dpryan79** [comment]
This can be merged on Monday after the local indices are actually generated.

**Comment by katsikora** [comment]
do you mean 2.7.3a instead of 2.7.1a by any chance?

**Comment by dpryan79** [comment]
No, since if we're going to make subdirectories we should use the earliest version that supported an index format for the name.

**Comment by katsikora** [comment]
ok, then I'll rename it in my PR to data_repository

**Pull request merged**
