### PR TITLE
fix #785

### LINKED ISSUE #785: estimateReadFiltering: assign more resources
Someone in our group just ran the ChIP-seq workflow and the estimateReadfiltering step takes forever. We need to assign more threads to the step (currently 1)

### PR DESCRIPTION
**Pull request by vivekbhr**
closes #785

### CODE REVIEW

**Comment by LeilyR** [comment]
why do you want to hard code 10?

**Comment by vivekbhr** [comment]
> why do you want to hard code 10?

I wanted to use the 'mapq' variable, but is not available in ChIP-seq workflow

**Comment by LeilyR** [comment]
> > why do you want to hard code 10?
> 
> I wanted to use the 'mapq' variable, but is not available in ChIP-seq workflow

I see, want me quickly add it to both default.yaml and the ChIP-seq file?

**Comment by vivekbhr** [comment]
This option will not allow users to filter for the mapq in the ChIP-seq workflow (like in DNA-mapping), only check the reads below mapq in estimatereadFiltering. So it won't be much useful at the end.

btw do you want me to fix #783 while I fix the CI errors? we can push these 2 update together as a bugfix release then

**Comment by LeilyR** [comment]
> This option will not allow users to filter for the mapq in the ChIP-seq workflow (like in DNA-mapping), only check the reads below mapq in estimatereadFiltering. So it won't be much useful at the end.
> 
> btw do you want me to fix #783 while I fix the CI errors? we can push these 2 update together as a bugfix release then

OK, as you wish, then you cna ignore my PR on that.
Regarding the #783 , sure go ahead that would be great

**Comment by vivekbhr** [comment]
finally CI fixed. @LeilyR feel free to merge

**Comment by vivekbhr** [comment]
@LeilyR feel free to merge

**Comment by katsikora** [comment]
Hi guys,
is this PR still pending, or would you like to close it?
Best,
Katarzyna

**Comment by LeilyR** [comment]
this PR can be closed but bear in mind that #783 issue is still in place

**Pull request closed without merging**
