### PR TITLE
Remove Picard. It's still in the WGBS pipeline, but that can be saved…

### LINKED ISSUE #272: Remove Picard AlignmentSummaryMetrics from DNA mapping pipeline
The same information is already in the Bowtie2 output and/or idxstats. This is used by the ChIP and ATAC workflows, so they would need to be tested.

### PR DESCRIPTION
**Pull request by dpryan79**
… for later.

To test:

 - [x] DNA-mapping
 - [x] ChIP-seq
 - [x] ATAC-seq

Closes #272

### CODE REVIEW

**Comment by katsikora** [comment]
so Picard is not anymore in the WGBS pipe, since quite some time (sambamba is used)

**Comment by dpryan79** [comment]
@katsikora You still use `picard CreateSequenceDictionary`.

**Comment by dpryan79** [comment]
Though I guess that's if you have to create a new reference, which was superseded by `createIndices`.

**Comment by katsikora** [comment]
ah yes, that's correct... this is one to-do to fully replace custom reference conversion by createIndices (it would still require Picard though - because of GATK...)

**Comment by dpryan79** [comment]
@katsikora You can replace that with `samtools dict`. I don't actually do that in `createIndices`, but can if you need it for the WGBS pipeline.

**Comment by dpryan79** [comment]
The dictionary is now made in `createIndices`.

**Pull request merged**
