### PR TITLE
Restructure everything, reduce code duplication, streamline installation

### PR DESCRIPTION
**Pull request by dpryan79**
This is what's needed to streamline installation as outlined in #110. SnakePipes is now a python package and all of the yaml and other files are now installed as package data. This requires heavily restructuring things. On the plus side one can now `pip install` this and use an included program (`snakePipes`) to list the location of relevant YAML files and create the conda environments (this then modifies the YAML files). Each of the workflows will need to be modified to actually work with this.

### CODE REVIEW

**Comment by dpryan79** [comment]
Before this ends up getting merged I'll move the `snakemake_options` from the workflow-specific `defaults.yaml` and put it somewhere else.

**Comment by dpryan79** [comment]
The following workflows work at the moment: ATAC-seq, ChIP-seq and DNA-mapping.

**Comment by dpryan79** [comment]
RNA-seq and WGBS now work. HiC sort of does but the test dataset throws an error due to not being able to make a MAD at some point.

**Comment by katsikora** [comment]
Ok to set trimming in WGBS to 'user' as default. Just keep the 'auto' option in, I might need it from time to time.

**Pull request merged**
