### PR TITLE
ruamel - fix ChIPtests

### PR DESCRIPTION
**Pull request by WardDeb**
Should take care of the pytest issues with SEACR runs, and all the ones where the jobcount is also aberrant.
ruamel is not an explicit dependency yet. Testing wether this should be the case.

### CODE REVIEW

**Comment by WardDeb** [comment]
I did run into something that I think is a bug, running ChIP-seq without a sampleSheet now errors out:

```
○ → ChIP-seq -d bam_input/ --snakemakeOptions "--dryrun --conda-prefix /tmp -q " org.yaml chipdict.yaml

---- This analysis has been done using snakePipes version 2.7.3 ----
/localenv/deboutte/anaconda/miniconda/envs/snakepipes_dev/lib/python3.9/site-packages/snakePipes/workflows/ChIP-seq/internals.snakefile:143: UserWarning: 6 out of 6 have a matching control 
  warnings.warn( str(len(chip_samples_w_ctrl)) + " out of " + str(len(chip_samples)) + " have a matching control ")
NameError in line 160 of /localenv/deboutte/anaconda/miniconda/envs/snakepipes_dev/lib/python3.9/site-packages/snakePipes/shared/rules/ChIP_peak_calling.snakefile:
name 'isMultipleComparison' is not defined
  File "/localenv/deboutte/anaconda/miniconda/envs/snakepipes_dev/lib/python3.9/site-packages/snakePipes/workflows/ChIP-seq/Snakefile", line 43, in <module>
  File "/localenv/deboutte/anaconda/miniconda/envs/snakepipes_dev/lib/python3.9/site-packages/snakePipes/shared/rules/ChIP_peak_calling.snakefile", line 160, in <module>
Error: snakemake returned an error code of 1, so processing is incomplete!
```

**Comment by katsikora** [comment]
Thanks a lot for your help!

**Comment by katsikora** [comment]
> I did run into something that I think is a bug, running ChIP-seq without a sampleSheet now errors out, this wasn't the case in 2.7.2, I've added a test for this, but the bug itself is not fixed yet.
> 
> ```
> ○ → ChIP-seq -d bam_input/ --snakemakeOptions "--dryrun --conda-prefix /tmp -q " org.yaml chipdict.yaml
> 
> ---- This analysis has been done using snakePipes version 2.7.3 ----
> /localenv/deboutte/anaconda/miniconda/envs/snakepipes_dev/lib/python3.9/site-packages/snakePipes/workflows/ChIP-seq/internals.snakefile:143: UserWarning: 6 out of 6 have a matching control 
>   warnings.warn( str(len(chip_samples_w_ctrl)) + " out of " + str(len(chip_samples)) + " have a matching control ")
> NameError in line 160 of /localenv/deboutte/anaconda/miniconda/envs/snakepipes_dev/lib/python3.9/site-packages/snakePipes/shared/rules/ChIP_peak_calling.snakefile:
> name 'isMultipleComparison' is not defined
>   File "/localenv/deboutte/anaconda/miniconda/envs/snakepipes_dev/lib/python3.9/site-packages/snakePipes/workflows/ChIP-seq/Snakefile", line 43, in <module>
>   File "/localenv/deboutte/anaconda/miniconda/envs/snakepipes_dev/lib/python3.9/site-packages/snakePipes/shared/rules/ChIP_peak_calling.snakefile", line 160, in <module>
> Error: snakemake returned an error code of 1, so processing is incomplete!
> ```

I'll take care of that on Monday :+1:

**Review by katsikora — APPROVED** [review]

**Comment by katsikora** [comment]
Feel free to merge as it is, it looks great!

**Pull request merged**
