### PR TITLE
Make the organism directory and cluster yaml configurable.

### LINKED ISSUE #439: Make the organisms directory configurable
At the moment, the organisms yaml files can be either placed under `shared/organisms` or an absolute path provided. What I hadn't considered is people wanting to upgrade snakePipes in places (I ALWAYS create new environments for each software version), which will overwrite any changes people make to the organism yaml files. What would be better is if `shared/defaults.yaml` had an `organisms` entry specifying the relative or absolute path to a directory containing the organisms yaml file.

Additionally, we should move snakemake cluster commands from `cluster.yaml` to `defaults.yaml`. Then only `defaults.yaml` needs to be touched by users when they install/upgrade.

### PR DESCRIPTION
**Pull request by dpryan79**
Closes #439 

 - [x] Tested with defaults
   - [x] ChIP-seq
   - [x] createIndices
   - [x] DNA-mapping
   - [x] HiC
   - [x] RNA-seq
   - [x] scRNAseq
   - [x] WGBS
 - [x] Tested with absolute paths
   - [x] ChIP-seq
   - [x] createIndices
   - [x] DNA-mapping
   - [x] HiC
   - [x] RNA-seq
   - [x] scRNAseq
   - [x] WGBS
 - [x] Documentation added

### CODE REVIEW

**Comment by dpryan79** [comment]
@steffenheyne What do you think about this? In essence, we add lines to default.yaml saying where to find organism yaml files and the cluster config file. Upon update, someone only needs to edit this single file then and change two lines. This should allow absolute paths to be used (I have to test it all), so external users can just make a directory somewhere and keep all of their stuff there so they don't have to worry about upgrades breaking things.

**Comment by steffenheyne** [comment]
looks good!
At some point it would be good I think to also make things like `organismDir` and `clusterConfig` etc in defaults.yaml configurable via bin/snakePipes at the cmd line. So no need to find the right files for a user etc

**Comment by dpryan79** [comment]
We could probably make a `snakePipes config` command for that. It would just source that file as the defaults and then rewrite it.

**Comment by dpryan79** [comment]
The good news is that we can now test to ensure that ALL environments are solvable on OSX and Linux. The bad news is that I forgot to build and upload splitFastq for OSX.

**Comment by dpryan79** [comment]
Meh, I'll fix the ATAC-seq pipeline in a separate PR.

**Pull request merged**
