### PR TITLE
Use GTF files with featureCounts, don't always always compute the gen…

### LINKED ISSUE #90: Why are we modify GTF files by default?
Is there a reason that GTF files are munged beyond recognition in the RNA-seq workflow? They're fine as is for bulk RNA-seq and we can't even report that "we used Gencode m15" in the methods if we modify the crap out of them.

### PR DESCRIPTION
**Pull request by dpryan79**
…omic contamination in the RNAseq pipeline

This fixes #90 and an additional bug wherein the genomic contamination stuff is always run, regardless whether one specifies `-GC` or not.

### CODE REVIEW

**Comment by steffenheyne** [comment]
current RNA-seq workflow has the option "--filter_annotation" to allow for pre-filtering of the provided organism gtf file. the rules for this filtering are in "filter_annotation.snakefle". I think the idea of this oiption was to pre-filter the given annotation for eg. pseudogenes and the count only remaining genes/exons etc. 

following this idea, in filter_annotation.snakefile", in rule "create_annotation_bed", a "genes.annotated.bed" (actually a transcripts.annotated.bed file) with some additional columns like "gene_biotype" etc is created. This file can then be row-wise filtered with grep (rule filter_annotation_bed).

Hence, if we still want the cmdl option "--filter_annotation" for RNA-seq, we should use the  "Annoation/genes.filtered.gtf" file for featureCounts. This should be a correct gtf files with exon entries, only filtered to whatever the user provided. in case of no filtering, this should match the original exon entries in the gtf file from the organism config.

**Comment by steffenheyne** [comment]
I forgot to mention above that there is a rule "annotation_bed2gtf" that converts the filtered bed file back to gtf, which is then named "Annoation/genes.filtered.gtf".

**Comment by steffenheyne** [comment]
the output of rules "annotation_bed2t2g" and "annotation_bed2symbol" are used in DESeq2.snakefile and sleuth.snakefile. Here is principle we could provided unfiltered files and hence use as input to these rules "Annotation/genes.annotated.bed" instead of "Annotation/genes.filtered.bed". (eg in case we skip the filter_annotation option)

**Comment by vivekbhr** [comment]
genes.filtered.gtf should be general input to all tools (featurecounts/salmon-sleuth) where this file would be same as genes.gtf in case no filtering is asked for (the default)

**Comment by vivekbhr** [comment]
I changed the input file to filtered GTF [here](https://github.com/maxplanck-ie/snakepipes/commit/c076dab334a1ed8cc21bdb13900b4a7778a4873e) and @LeilyR fixed the genomic contam issue in #93 so I am closing this one.

**Pull request closed without merging**
